### ISSUE TITLE
Errors when trying to connect to a P1P

### ISSUE THREAD

**Issue by franklinvv** [hisptoot/BambuSource2Raw#4]
I have everything working properly with 2 X1Cs and now I'm trying to get this working on my P1P with firmware version 01.02.02.00. I'm following all directions from the README but unfortunately `bambusource2raw` is returning errors when trying to connect to the printer.

```starting rtsp-simple-server
wait for 5 seconds
starting bambusource2raw
ffmpeg version 5.1.1-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
by hisptoot 2022.12.26
p1p ip: <x.x.x.x>
access code specified by user
getting user info by BambuNetworkEngine.conf
region: eu user_id: <xxxxxxxxxx> dev_id: <xxxxxxxxxxxxxx>
Starting Session
[1] [BambuTunnelLocal::open] host=<x.x.x.x> port=6000
[1] [BambuTunnelTutk::read]  [-104]
[1] [BambuTunnel::read_sample] error [-104]
[1] [BambuTunnel::read_sample] error [1]
[1] [BambuTunnel::read_sample] error [1]
[1] [BambuTunnel::read_sample] error [1]
[1] [BambuTunnel::read_sample] error [1]
[1] [BambuTunnel::read_sample] error [1]
```

I have no idea what to do with this error. I just unpacked this P1P and updated the firmware to the latest version, so I can't tell whether this does work with an earlier firmware.

**Comment by hisptoot** [comment]
My P1P is a chinese version.

bambusource2raw works on 01.01.01.00. 
I upgrade the firmware to 01.02.02.00 today and it still works.

Two things to check first:

1.Make sure the version of libBambuSource.so is above 01.04.xx.xx. Early version doesn't support P1P.
  The error comes from libBambuSource.so. And it's weird that the log contains "[BambuTunnelTutk::read]".

2.Make sure ip address and access code are correct.

**Comment by hisptoot** [comment]
Just did some analysis on libBambuSource.so.

In version 01.03.01.02, BambuTunnelLocal::read will output "[BambuTunnelTutk::read] %s [%d]" when LocalTunnel_Read returns error.

In version 01.04.00.15, BambuTunnelLocal::read will output "[BambuTunnelLocal::read] %s [%d]" when LocalTunnel_Read returns error.

So I think you should upgrade libBambuSource.so to 01.04 or above. And the new version of libBambuSource.so requires GLIBC 2.28.

**Comment by franklinvv** [comment]
Hi @hisptoot, thanks for replying so quickly! Indeed, the problem on my side appears to have been an outdated `libBambuSource.so`. With the latest version, I can get it to work with a P1P, although only dockerized on the machine on which I have this installed. Probably due to the glibc constraint that you mentioned.

I will close this issue. Again, thank you!
