### ISSUE TITLE
Error trying to get device id.

### ISSUE THREAD

**Issue by AdrianGarside** [hisptoot/BambuSource2Raw#8]
Get dev id and access code of the machine
./bambusource2raw list_dev -u <account_name> -p <password> -r <region: us cn>

I'm using my email address - maybe it needs something else?

Output is:

by hisptoot 2022.12.26
user_name: REDACTED
passwd specified by user
region: us
getting token by login
getting user_id by token
curl_easy_perform() failed: Failed writing received data to disk/application
failed get_user_id
{"tfaKey":""}

**Comment by AdrianGarside** [comment]
Tried my user name as shown in makerworld and I get a different error that suggests my email address is the correct user name to use:

by hisptoot 2022.12.26
user_name: REDACTED
passwd specified by user
region: us
getting token by login
cookies is empty
get_user_token by login request failed
getting user info by BambuNetworkEngine.conf
BambuNetworkEngine.conf not exist
get_bambu_studio_user_info failed
{"code":1,"error":"This account is not registered."}

**Comment by hisptoot** [comment]
account_name is your email address in non-china regions.

The error comes from libcurl , something is wrong when processing the received data.  
Maybe the receive buffer is too small in this case. 

I modified a linux version to use dynamically allocated buffer, you can have a try.
[BambuSource2Raw-2023-11-14-for-test.zip](https://github.com/hisptoot/BambuSource2Raw/files/13344161/BambuSource2Raw-2023-11-14-for-test.zip)

**Comment by AdrianGarside** [comment]
Thanks. Will try it in a bit once back near my PC. I did double the buffer size and recompile but that didn’t help. Maybe that still wasn’t enough.

**Comment by AdrianGarside** [comment]
Copied your cpp changes over the original and recompiled it. This time it worked :).

**Comment by AdrianGarside** [comment]
Network config is failing with a different error. Previously I'd guessed (correctly) the device name but hit the same curl error trying to create the config. Now I don't get that but I still get an invalid pointer error that I also saw with that attempt.

by hisptoot 2023.08.02
user_name: REDACTED
passwd specified by user
region: us
dev_id: REDACTED
getting token by login
getting user_id by token
json len: 1323
user_id: REDACTED
region: us user_id: REDACTED dev_id: REDACTED
munmap_chunk(): invalid pointer
Aborted

However the config file seems to have been created despite this. And it looks to contain a valid authentication token.

**Comment by AdrianGarside** [comment]
Still not quite there:

./start_rtsp_feed_p1p.sh
starting bambusource2raw
by hisptoot 2023.08.02
ip: REDACTED
access code specified by user
getting user info by BambuNetworkEngine.conf
region: us user_id: REDACTED dev_id: REDACTED
Starting Session
[1] [BambuTunnelLocal::open] host=REDACTED port=6000
< ~5 second pause here >
[1] BambuTunnel::start_stream ok
< and then it exits >

**Comment by AdrianGarside** [comment]
In case it's relevant, I should add that currently Bambu Handy is pretty consistently giving me a connection failed error -22 when trying to view the camera. Bambu Studio is working though.

**Comment by hisptoot** [comment]
I modified a new version, it should fix the 'munmap_chunk(): invalid pointer' caused by freeing a wrong pointer and will output more detailed log from libbambusource.so.

[bambusource2raw-2023-11-14-for-test2.zip](https://github.com/hisptoot/BambuSource2Raw/files/13345404/bambusource2raw-2023-11-14-for-test2.zip)
use the libbambusource.so from https://public-cdn.bambulab.com/upgrade/studio/plugins/01.07.00.04/linux_01.07.00.04.zip

then run

./bambusource2raw start_local_stream -s [p1p_ip_addr] -a [access_code] >/dev/null

see what happens

**Comment by AdrianGarside** [comment]
No error this time when generating the network config:

by hisptoot 2023.08.02
user_name: adriangarside@outlook.com
passwd specified by user
region: us
dev_id: REDACTED
getting token by login
getting user_id by token
json len: 1323
user_id: REDACTED
region: us user_id: REDACTED dev_id: REDACTED
{"tfaKey":""}

Updated libBambuSource.so (one I was using was older):
New:  4710400 Jul 12 09:02 libBambuSource.so
Old:  4624352 Dec 14  2022 libBambuSource.so

Starting the stream crashed:

./bambusource2raw start_local_stream -s 10.10.10.81 -a REDACTED >/dev/null
by hisptoot 2023.08.02
ip: 10.10.10.81
access code specified by user
getting user info by BambuNetworkEngine.conf
region: us user_id: REDACTED dev_id: REDACTED
json len: 131
Starting Session
[3] [BambuTunnelTutk::open] IOTC_Connect_ByUIDEx(VGE93SRC6KDR4PY2111A).......
Illegal instruction

**Comment by hisptoot** [comment]
Sorry, my fault.
The command line should be

./bambusource2raw start_stream_local -s [p1p_ip_addr] -a [access_code] >/dev/null

**Comment by AdrianGarside** [comment]
Nothing obvious jumping out as wrong. And I see binary data if I don't pipe to /dev/null

by hisptoot 2023.08.02
ip: 10.10.10.81
access code specified by user
getting user info by BambuNetworkEngine.conf
region: us user_id: REDACTED dev_id: REDACTED
Starting Session
[1] [BambuTunnelLocal::open] host=10.10.10.81 port=6000
[2] [BambuTunnel::read_sample] buffer limit [48000]
[3] [BambuTunnel::read_sample] would block [1]
[1] BambuTunnel::start_stream ok
[3] [BambuTunnel::read_sample] would block [2]
[3] [BambuTunnel::read_sample] would block [4]
[3] [BambuTunnel::read_sample] would block [8]
And every so often I get more of those read_sample lines with varying powers of two value up to 16.

So it seems to be an issue with the pipe in ffmpeg?

**Comment by AdrianGarside** [comment]
Oh... my ffmpeg exe is zero bytes in size. That's not gonna work...!

**Comment by AdrianGarside** [comment]
Progress. ffmpeg doesn't like the -c parameter:

ffmpeg version 6.0.1-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
-c: No such file or directory
by hisptoot 2023.08.02
ip: 10.10.10.81
access code specified by user
getting user info by BambuNetworkEngine.conf
region: us user_id: REDACTED dev_id: REDACTED
Starting Session
[1] [BambuTunnelLocal::open] host=10.10.10.81 port=6000
[2] [BambuTunnel::read_sample] buffer limit [48000]
[3] [BambuTunnel::read_sample] would block [1]
[1] BambuTunnel::start_stream ok

**Comment by AdrianGarside** [comment]
And that was my mistake. I misunderstood the ffmpeg instructions and only copied the single executable over instead of extracting the entire tar file into the linux-build directory.

It's now running without errors/early exit. But I can't yet connect via vlc:

Your input can't be opened:
VLC is unable to open the MRL 'rtsp://192.168.0.5:8554/bbl'. Check the log for details.

Ctrl-C shows some data from one of the tools that shows it successfully detected the type and resolution of the video:

Starting Session
[1] [BambuTunnelLocal::open] host=10.10.10.81 port=6000
[2] [BambuTunnel::read_sample] buffer limit [48000]
[3] [BambuTunnel::read_sample] would block [1]
[1] BambuTunnel::start_stream ok
[3] [BambuTunnel::read_sample] would block [2]
[3] [BambuTunnel::read_sample] would block [4]
[3] [BambuTunnel::read_sample] would block [8]
^CInput #0, jpeg_pipe, from 'fd:':
  Duration: N/A, bitrate: N/A
  Stream #0:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 1280x720 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 25 tbn
[out#0/rtsp @ 0x7b74fc0] Could not write header (incorrect codec parameters ?): Immediate exit requested
[vost#0:0/copy @ 0x7b726c0] Error initializing output stream:
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
    Last message repeated 1 times
Exiting normally, received signal 2.

Is anything extra needed to be able to view the stream from another machine instead of localhost? I can get vlc installed to the VM if running it locally against 127.0.0.1 would be useful for narrowing down the remaining issue.

**Comment by hisptoot** [comment]
ffmpeg will publish the stream to rtsp-simple-server. rtsp-simple-server will provide a rtsp stream for vlc client.

In this case, check the log of ffmpeg and rtsp-simple-server.

In a terminal, run:
`./rtsp-simple-server`

In another terminal, run:
` ./bambusource2raw start_stream_local -s [ip_addr_of_p1p] -a [access_code] | ./ffmpeg -i - -c copy -f rtsp rtsp://127.0.0.1:8554/bbl`

If everything is properly set, it should output:

> 
> 2023/11/15 09:37:33 INF rtsp-simple-server v0.20.0
> 2023/11/15 09:37:33 INF [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)
> 2023/11/15 09:37:33 INF [RTMP] listener opened on :1935
> 2023/11/15 09:37:33 INF [HLS] listener opened on :8888
> 2023/11/15 09:38:35 INF [RTSP] [conn 127.0.0.1:43280] opened
> 2023/11/15 09:38:35 INF [RTSP] [session 857210451] created by 127.0.0.1:43280
> 2023/11/15 09:38:35 INF [RTSP] [session 857210451] is publishing to path 'bbl', with UDP, 1 track (JPEG)
> 2023/11/15 09:38:55 INF [RTSP] [conn 192.168.12.35:54475] opened
> 2023/11/15 09:38:55 INF [RTSP] [session 661146571] created by 192.168.12.35:54475
> 2023/11/15 09:38:55 INF [RTSP] [session 661146571] is reading from path 'bbl', with UDP, 1 track (JPEG)


> ffmpeg version 6.0.1-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2023 the FFmpeg developers
>   built with gcc 8 (Debian 8.3.0-6)
>   configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
>   libavutil      58.  2.100 / 58.  2.100
>   libavcodec     60.  3.100 / 60.  3.100
>   libavformat    60.  3.100 / 60.  3.100
>   libavdevice    60.  1.100 / 60.  1.100
>   libavfilter     9.  3.100 /  9.  3.100
>   libswscale      7.  1.100 /  7.  1.100
>   libswresample   4. 10.100 /  4. 10.100
>   libpostproc    57.  1.100 / 57.  1.100
> by hisptoot 2023.08.02
> ip: 192.168.12.34
> access code specified by user
> getting user info by BambuNetworkEngine.conf
> region: cn user_id: xxxxxxxx dev_id: xxxxxxxx
> Starting Session
> [1] [BambuTunnelLocal::open] host=192.168.12.34 port=6000
> [2] [BambuTunnel::read_sample] buffer limit [48000]
> [3] [BambuTunnel::read_sample] would block [1]
> [1] BambuTunnel::start_stream ok
> [3] [BambuTunnel::read_sample] would block [2]
> [3] [BambuTunnel::read_sample] would block [4]
> [3] [BambuTunnel::read_sample] would block [8]
> Input #0, jpeg_pipe, from 'fd:':
>   Duration: N/A, bitrate: N/A
>   Stream #0:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 1280x720 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 25 tbn
> Output #0, rtsp, to 'rtsp://127.0.0.1:8554/bbl':
>   Metadata:
>     encoder         : Lavf60.3.100
>   Stream #0:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 90k tbn
> Stream mapping:
>   Stream #0:0 -> #0:0 (copy)
> frame=   79 fps=2.8 q=-1.0 Lsize=N/A time=00:00:03.12 bitrate=N/A speed=0.111x

ffmpeg may be a little slow to start publishing the stream. I think it's probesize or buffer related.

If you still can not connect, then check if the tcp port is accessible:
`telnet [ip_addr_of_rtsp_server] 8554`

**Comment by AdrianGarside** [comment]
I see this output from rtsp-simple-server when I attempt to connect via vlc:

adrian@HomeAssistant:~/repo/BambuSource2Raw/linux-build$ ./rtsp-simple-server
2023/11/14 18:12:27 INF rtsp-simple-server v0.20.0
2023/11/14 18:12:27 INF [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)
2023/11/14 18:12:27 INF [RTMP] listener opened on :1935
2023/11/14 18:12:27 INF [HLS] listener opened on :8888
<CONNECTION ATTEMPT STARTED>
2023/11/14 18:13:40 INF [RTSP] [conn 192.168.0.10:64599] opened
2023/11/14 18:13:40 INF [RTSP] [conn 192.168.0.10:64599] closed **(no one is publishing to path 'bbl')**
2023/11/14 18:13:40 INF [RTSP] [conn 192.168.0.10:64600] opened
2023/11/14 18:13:40 INF [RTSP] [session 648561575] created by 192.168.0.10:64600
2023/11/14 18:13:40 INF [RTSP] [session 648561575] destroyed (not in use)
2023/11/14 18:13:40 INF [RTSP] [conn 192.168.0.10:64600] closed (path of a SETUP request must end with a slash. This typically happens when VLC fails a request, and then switches to an unsupported RTSP dialect)
2023/11/14 18:13:40 INF [RTSP] [conn 192.168.0.10:64601] opened
2023/11/14 18:13:40 INF [RTSP] [conn 192.168.0.10:64601] closed (EOF)

Oh... just started getting video playback output from BambuSource2Raw:

[3] [BambuTunnel::read_sample] would block [16]
Input #0, jpeg_pipe, from 'fd:':
  Duration: N/A, bitrate: N/A
  Stream #0:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 1280x720 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 25 tbn
Output #0, rtsp, to 'rtsp://127.0.0.1:8554/bbl':
  Metadata:
    encoder         : Lavf60.3.100
  Stream #0:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 90k tbn
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
frame=    0 fps=0.0 q=-1.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=  frame=   65 fps= 17 q=-1.0 size=N/A time=00:00:02.60 bitrate=N/A speed=0.673x   frame=   67 fps=8.4 q=-1.0 size=N/A time=00:00:02.68 bitrate=N/A speed=0.337x   frame=   68 fps=6.8 q=-1.0 size=N/A time=00:00:02.72 bitrate=N/A speed=0.273x   frame=   69 fps=5.8 q=-1.0 size=N/A time=00:00:02.76 bitrate=N/A speed=0.23frame=   70 fps=5.0 q=-1.0 size=N/A time=00:00:02.80 bitrate=N/A speed=0.201x  frame=   71 fps=4.5 q=-1.0 size=N/A time=00:00:02.84 bitrate=N/A speed=0.179x  frame=   72 fps=4.1 q=-1.0 size=N/A time=00:00:02.88 bitrate=N/A speed=0.162x  frame=   73 fps=3.7 q=-1.0 size=N/A time=00:00:02.92 bitrate=N/A speed=0.149x 

And I can now load the stream in VLC!

So there was just a long delay (~2 minutes) before the video started being published:

2023/11/14 18:13:40 INF [RTSP] [conn 192.168.0.10:64601] closed (EOF)
2023/11/14 18:15:29 INF [RTSP] [conn 127.0.0.1:50604] opened
2023/11/14 18:15:29 INF [RTSP] [session 100246689] created by 127.0.0.1:50604
2023/11/14 18:15:29 INF [RTSP] [session 100246689] is publishing to path 'bbl', with UDP, 1 track (JPEG)
2023/11/14 18:16:42 INF [RTSP] [conn 192.168.0.10:64693] opened
2023/11/14 18:16:42 INF [RTSP] [session 488445423] created by 192.168.0.10:64693
2023/11/14 18:16:42 INF [RTSP] [session 488445423] is reading from path 'bbl', with UDP, 1 track (JPEG)

Apparently I just needed to be more patient (I try to be but things take too long). I'm surprised earlier attempts didn't work since I left BambuSource2Raw running for a while at one point to see if it printed anything more than the 'would block' lines.

**Comment by AdrianGarside** [comment]
I'm going to close this as fixed. Thank you for the help addressing the blocking bugs. And hopefully my experiences will help others that mistake initialization delays for not working.

Now if only I could get Home Assistant's camera integration to not consistently time out trying to add the camera.

**Comment by hisptoot** [comment]
add the following options to ffmpeg:

`-fflags nobuffer -flags low_delay -analyzeduration 10 -probesize 3200`

it should speed up the initialization.


` ./bambusource2raw start_stream_local -s [ip_addr_of_p1p] -a [access_code] | ./ffmpeg -fflags nobuffer -flags low_delay -analyzeduration 10 -probesize 3200 -i - -c copy -f rtsp rtsp://127.0.0.1:8554/bbl`

**Comment by AdrianGarside** [comment]
Yes. Way faster. Faster than I could get to the already open VLC window and try to connect :). Under a second from the first 'would block' log output to the video feed related logging.
